# Generated by Django 3.2 on 2021-07-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
