# Generated by Django 3.2 on 2021-07-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
