# Generated by Django 3.2 on 2021-07-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contact_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_read',
        ),
        migrations.CreateModel(
            name='Emailnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField(choices=[('1', 'Email')])),
                ('text_prewiev', models.CharField(blank=True, max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifi_from_user', to='app.contact')),
            ],
        ),
    ]
