# Generated by Django 3.2 on 2021-07-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210708_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='notification_type',
            field=models.CharField(choices=[('1', 'Email')], max_length=250),
        ),
    ]
