# Generated by Django 3.2 on 2021-07-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_emailnotification_notification_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emailnotification',
        ),
    ]
