# Generated by Django 3.2 on 2021-07-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_emailnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='like',
        ),
    ]
