# Generated by Django 3.2 on 2021-07-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_blogpost_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
